<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:v="urn:local:vocab"
                version="3.0"
                exclude-result-prefixes="#all">
  <xsl:variable name="v:marcmusperf" as="map(xs:string, text())">
    <!-- https://www.loc.gov/standards/valuelist/marcmusperf.html -->
    <xsl:map>
      <xsl:map-entry key="'ba'">Brass - Horn</xsl:map-entry>
      <xsl:map-entry key="'bb'">Brass - Trumpet</xsl:map-entry>
      <xsl:map-entry key="'bc'">Brass - Cornet</xsl:map-entry>
      <xsl:map-entry key="'bd'">Brass - Trombone</xsl:map-entry>
      <xsl:map-entry key="'be'">Brass - Tuba</xsl:map-entry>
      <xsl:map-entry key="'bf'">Brass - Baritone</xsl:map-entry>
      <xsl:map-entry key="'bn'">Brass - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'bu'">Brass - Unknown</xsl:map-entry>
      <xsl:map-entry key="'by'">Brass - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'bz'">Brass - Other</xsl:map-entry>
      <xsl:map-entry key="'ca'">Choruses - Mixed</xsl:map-entry>
      <xsl:map-entry key="'cb'">Choruses - Women's</xsl:map-entry>
      <xsl:map-entry key="'cc'">Choruses - Men's</xsl:map-entry>
      <xsl:map-entry key="'cd'">Choruses - Children's</xsl:map-entry>
      <xsl:map-entry key="'cn'">Choruses - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'cu'">Choruses - Unknown</xsl:map-entry>
      <xsl:map-entry key="'cy'">Choruses - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'ea'">Electronic - Synthesizer</xsl:map-entry>
      <xsl:map-entry key="'eb'">Electronic - Tape</xsl:map-entry>
      <xsl:map-entry key="'ec'">Electronic - Computer</xsl:map-entry>
      <xsl:map-entry key="'ed'">Electronic - Ondes Martinot</xsl:map-entry>
      <xsl:map-entry key="'en'">Electronic - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'eu'">Electronic - Unknown</xsl:map-entry>
      <xsl:map-entry key="'ez'">Electronic - Other</xsl:map-entry>
      <xsl:map-entry key="'ka'">Keyboard - Piano</xsl:map-entry>
      <xsl:map-entry key="'kb'">Keyboard - Organ</xsl:map-entry>
      <xsl:map-entry key="'kc'">Keyboard - Harpsichord</xsl:map-entry>
      <xsl:map-entry key="'kd'">Keyboard - Clavichord</xsl:map-entry>
      <xsl:map-entry key="'ke'">Keyboard - Continuo</xsl:map-entry>
      <xsl:map-entry key="'kf'">Keyboard - Celeste</xsl:map-entry>
      <xsl:map-entry key="'kn'">Keyboard - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'ku'">Keyboard - Unknown</xsl:map-entry>
      <xsl:map-entry key="'ky'">Keyboard - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'kz'">Keyboard - Other</xsl:map-entry>
      <xsl:map-entry key="'oa'">Larger ensemble - Full orchestra</xsl:map-entry>
      <xsl:map-entry key="'ob'">Larger ensemble - Chamber orch.</xsl:map-entry>
      <xsl:map-entry key="'oc'">Larger ensemble - String orchestra</xsl:map-entry>
      <xsl:map-entry key="'od'">Larger ensemble - Band</xsl:map-entry>
      <xsl:map-entry key="'oe'">Larger ensemble - Dance orchestra</xsl:map-entry>
      <xsl:map-entry key="'of'">Larger ensemble - Brass band (brass with some doubling, with or without percussion)</xsl:map-entry>
      <xsl:map-entry key="'on'">Larger ensemble - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'ou'">Larger ensemble - Unknown</xsl:map-entry>
      <xsl:map-entry key="'oy'">Larger ensemble - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'oz'">Larger ensemble - Other</xsl:map-entry>
      <xsl:map-entry key="'pa'">Percussion - Timpani</xsl:map-entry>
      <xsl:map-entry key="'pb'">Percussion - Xylophone</xsl:map-entry>
      <xsl:map-entry key="'pc'">Percussion - Marimba</xsl:map-entry>
      <xsl:map-entry key="'pd'">Percussion - Drum</xsl:map-entry>
      <xsl:map-entry key="'pn'">Percussion - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'pu'">Percussion - Unknown</xsl:map-entry>
      <xsl:map-entry key="'py'">Percussion - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'pz'">Percussion - Other</xsl:map-entry>
      <xsl:map-entry key="'sa'">Strings, bowed - Violin</xsl:map-entry>
      <xsl:map-entry key="'sb'">Strings, bowed - Viola</xsl:map-entry>
      <xsl:map-entry key="'sc'">Strings, bowed - Violoncello</xsl:map-entry>
      <xsl:map-entry key="'sd'">Strings, bowed - Double bass</xsl:map-entry>
      <xsl:map-entry key="'se'">Strings, bowed - Viol</xsl:map-entry>
      <xsl:map-entry key="'sf'">Strings, bowed - Viola d'amore</xsl:map-entry>
      <xsl:map-entry key="'sg'">Strings, bowed - Viola da gamba</xsl:map-entry>
      <xsl:map-entry key="'sn'">Strings, bowed - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'su'">Strings, bowed - Unknown</xsl:map-entry>
      <xsl:map-entry key="'sy'">Strings, bowed - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'sz'">Strings, bowed - Other</xsl:map-entry>
      <xsl:map-entry key="'ta'">Strings, plucked - Harp</xsl:map-entry>
      <xsl:map-entry key="'tb'">Strings, plucked - Guitar</xsl:map-entry>
      <xsl:map-entry key="'tc'">Strings, plucked - Lute</xsl:map-entry>
      <xsl:map-entry key="'td'">Strings, plucked - Mandolin</xsl:map-entry>
      <xsl:map-entry key="'tn'">Strings, plucked - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'tu'">Strings, plucked - Unknown</xsl:map-entry>
      <xsl:map-entry key="'ty'">Strings, plucked - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'tz'">Strings, plucked - Other</xsl:map-entry>
      <xsl:map-entry key="'va'">Voices - Soprano</xsl:map-entry>
      <xsl:map-entry key="'vb'">Voices - Mezzo Soprano</xsl:map-entry>
      <xsl:map-entry key="'vc'">Voices - Alto</xsl:map-entry>
      <xsl:map-entry key="'vd'">Voices - Tenor</xsl:map-entry>
      <xsl:map-entry key="'ve'">Voices - Baritone</xsl:map-entry>
      <xsl:map-entry key="'vf'">Voices - Bass</xsl:map-entry>
      <xsl:map-entry key="'vg'">Voices - Counter tenor</xsl:map-entry>
      <xsl:map-entry key="'vh'">Voices - High voice</xsl:map-entry>
      <xsl:map-entry key="'vi'">Voices - Medium voice</xsl:map-entry>
      <xsl:map-entry key="'vj'">Voices - Low voice</xsl:map-entry>
      <xsl:map-entry key="'vn'">Voices - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'vu'">Voices - Unknown</xsl:map-entry>
      <xsl:map-entry key="'vy'">Voices - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'wa'">Woodwinds - Flute</xsl:map-entry>
      <xsl:map-entry key="'wb'">Woodwinds - Oboe</xsl:map-entry>
      <xsl:map-entry key="'wc'">Woodwinds - Clarinet</xsl:map-entry>
      <xsl:map-entry key="'wd'">Woodwinds - Bassoon</xsl:map-entry>
      <xsl:map-entry key="'we'">Woodwinds - Piccolo</xsl:map-entry>
      <xsl:map-entry key="'wf'">Woodwinds - English horn</xsl:map-entry>
      <xsl:map-entry key="'wg'">Woodwinds - Bass clarinet</xsl:map-entry>
      <xsl:map-entry key="'wh'">Woodwinds - Recorder</xsl:map-entry>
      <xsl:map-entry key="'wi'">Woodwinds - Saxophone</xsl:map-entry>
      <xsl:map-entry key="'wn'">Woodwinds - Unspecified</xsl:map-entry>
      <xsl:map-entry key="'wu'">Woodwinds - Unknown</xsl:map-entry>
      <xsl:map-entry key="'wy'">Woodwinds - Ethnic</xsl:map-entry>
      <xsl:map-entry key="'wz'">Woodwinds - Other</xsl:map-entry>
      <xsl:map-entry key="'zn'">Unspecified instruments</xsl:map-entry>
      <xsl:map-entry key="'zu'">Unknown</xsl:map-entry>
    </xsl:map>
  </xsl:variable>
</xsl:stylesheet>
