<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:v="urn:local:vocab"
                version="3.0"
                exclude-result-prefixes="#all">
  <xsl:variable name="v:relators" as="map(xs:string, text())">
    <!-- https://id.loc.gov/vocabulary/relators.html -->
    <xsl:map>
      <xsl:map-entry key="'abr'">Abridger</xsl:map-entry>
      <xsl:map-entry key="'acp'">Art copyist</xsl:map-entry>
      <xsl:map-entry key="'act'">Actor</xsl:map-entry>
      <xsl:map-entry key="'adi'">Art director</xsl:map-entry>
      <xsl:map-entry key="'adp'">Adapter</xsl:map-entry>
      <xsl:map-entry key="'aft'">Author of afterword, colophon, etc.</xsl:map-entry>
      <xsl:map-entry key="'anc'">Announcer</xsl:map-entry>
      <xsl:map-entry key="'anl'">Analyst</xsl:map-entry>
      <xsl:map-entry key="'anm'">Animator</xsl:map-entry>
      <xsl:map-entry key="'ann'">Annotator</xsl:map-entry>
      <xsl:map-entry key="'ant'">Bibliographic antecedent</xsl:map-entry>
      <xsl:map-entry key="'ape'">Appellee</xsl:map-entry>
      <xsl:map-entry key="'apl'">Appellant</xsl:map-entry>
      <xsl:map-entry key="'app'">Applicant</xsl:map-entry>
      <xsl:map-entry key="'aqt'">Author in quotations or text abstracts</xsl:map-entry>
      <xsl:map-entry key="'arc'">Architect</xsl:map-entry>
      <xsl:map-entry key="'ard'">Artistic director</xsl:map-entry>
      <xsl:map-entry key="'arr'">Arranger</xsl:map-entry>
      <xsl:map-entry key="'art'">Artist</xsl:map-entry>
      <xsl:map-entry key="'asg'">Assignee</xsl:map-entry>
      <xsl:map-entry key="'asn'">Associated name</xsl:map-entry>
      <xsl:map-entry key="'ato'">Autographer</xsl:map-entry>
      <xsl:map-entry key="'att'">Attributed name</xsl:map-entry>
      <xsl:map-entry key="'auc'">Auctioneer</xsl:map-entry>
      <xsl:map-entry key="'aud'">Author of dialog</xsl:map-entry>
      <xsl:map-entry key="'aue'">Audio engineer</xsl:map-entry>
      <xsl:map-entry key="'aui'">Author of introduction, etc.</xsl:map-entry>
      <xsl:map-entry key="'aup'">Audio producer</xsl:map-entry>
      <xsl:map-entry key="'aus'">Screenwriter</xsl:map-entry>
      <xsl:map-entry key="'aut'">Author</xsl:map-entry>
      <xsl:map-entry key="'bdd'">Binding designer</xsl:map-entry>
      <xsl:map-entry key="'bjd'">Bookjacket designer</xsl:map-entry>
      <xsl:map-entry key="'bka'">Book artist</xsl:map-entry>
      <xsl:map-entry key="'bkd'">Book designer</xsl:map-entry>
      <xsl:map-entry key="'bkp'">Book producer</xsl:map-entry>
      <xsl:map-entry key="'blw'">Blurb writer</xsl:map-entry>
      <xsl:map-entry key="'bnd'">Binder</xsl:map-entry>
      <xsl:map-entry key="'bpd'">Bookplate designer</xsl:map-entry>
      <xsl:map-entry key="'brd'">Broadcaster</xsl:map-entry>
      <xsl:map-entry key="'brl'">Braille embosser</xsl:map-entry>
      <xsl:map-entry key="'bsl'">Bookseller</xsl:map-entry>
      <xsl:map-entry key="'cad'">Casting director</xsl:map-entry>
      <xsl:map-entry key="'cas'">Caster</xsl:map-entry>
      <xsl:map-entry key="'ccp'">Conceptor</xsl:map-entry>
      <xsl:map-entry key="'chr'">Choreographer</xsl:map-entry>
      <xsl:map-entry key="'cli'">Client</xsl:map-entry>
      <xsl:map-entry key="'cll'">Calligrapher</xsl:map-entry>
      <xsl:map-entry key="'clr'">Colorist</xsl:map-entry>
      <xsl:map-entry key="'clt'">Collotyper</xsl:map-entry>
      <xsl:map-entry key="'cmm'">Commentator</xsl:map-entry>
      <xsl:map-entry key="'cmp'">Composer</xsl:map-entry>
      <xsl:map-entry key="'cmt'">Compositor</xsl:map-entry>
      <xsl:map-entry key="'cnd'">Conductor</xsl:map-entry>
      <xsl:map-entry key="'cng'">Cinematographer</xsl:map-entry>
      <xsl:map-entry key="'cns'">Censor</xsl:map-entry>
      <xsl:map-entry key="'coe'">Contestant-appellee</xsl:map-entry>
      <xsl:map-entry key="'col'">Collector</xsl:map-entry>
      <xsl:map-entry key="'com'">Compiler</xsl:map-entry>
      <xsl:map-entry key="'con'">Conservator</xsl:map-entry>
      <xsl:map-entry key="'cop'">Camera operator</xsl:map-entry>
      <xsl:map-entry key="'cor'">Collection registrar</xsl:map-entry>
      <xsl:map-entry key="'cos'">Contestant</xsl:map-entry>
      <xsl:map-entry key="'cot'">Contestant-appellant</xsl:map-entry>
      <xsl:map-entry key="'cou'">Court governed</xsl:map-entry>
      <xsl:map-entry key="'cov'">Cover designer</xsl:map-entry>
      <xsl:map-entry key="'cpc'">Copyright claimant</xsl:map-entry>
      <xsl:map-entry key="'cpe'">Complainant-appellee</xsl:map-entry>
      <xsl:map-entry key="'cph'">Copyright holder</xsl:map-entry>
      <xsl:map-entry key="'cpl'">Complainant</xsl:map-entry>
      <xsl:map-entry key="'cpt'">Complainant-appellant</xsl:map-entry>
      <xsl:map-entry key="'cre'">Creator</xsl:map-entry>
      <xsl:map-entry key="'crp'">Correspondent</xsl:map-entry>
      <xsl:map-entry key="'crr'">Corrector</xsl:map-entry>
      <xsl:map-entry key="'crt'">Court reporter</xsl:map-entry>
      <xsl:map-entry key="'csl'">Consultant</xsl:map-entry>
      <xsl:map-entry key="'csp'">Consultant to a project</xsl:map-entry>
      <xsl:map-entry key="'cst'">Costume designer</xsl:map-entry>
      <xsl:map-entry key="'ctb'">Contributor</xsl:map-entry>
      <xsl:map-entry key="'cte'">Contestee-appellee</xsl:map-entry>
      <xsl:map-entry key="'ctg'">Cartographer</xsl:map-entry>
      <xsl:map-entry key="'ctr'">Contractor</xsl:map-entry>
      <xsl:map-entry key="'cts'">Contestee</xsl:map-entry>
      <xsl:map-entry key="'ctt'">Contestee-appellant</xsl:map-entry>
      <xsl:map-entry key="'cur'">Curator</xsl:map-entry>
      <xsl:map-entry key="'cwt'">Commentator for written text</xsl:map-entry>
      <xsl:map-entry key="'dbp'">Distribution place</xsl:map-entry>
      <xsl:map-entry key="'dfd'">Defendant</xsl:map-entry>
      <xsl:map-entry key="'dfe'">Defendant-appellee</xsl:map-entry>
      <xsl:map-entry key="'dft'">Defendant-appellant</xsl:map-entry>
      <xsl:map-entry key="'dgc'">Degree committee member</xsl:map-entry>
      <xsl:map-entry key="'dgg'">Degree granting institution</xsl:map-entry>
      <xsl:map-entry key="'dgs'">Degree supervisor</xsl:map-entry>
      <xsl:map-entry key="'dis'">Dissertant</xsl:map-entry>
      <xsl:map-entry key="'djo'">DJ</xsl:map-entry>
      <xsl:map-entry key="'dln'">Delineator</xsl:map-entry>
      <xsl:map-entry key="'dnc'">Dancer</xsl:map-entry>
      <xsl:map-entry key="'dnr'">Donor</xsl:map-entry>
      <xsl:map-entry key="'dpc'">Depicted</xsl:map-entry>
      <xsl:map-entry key="'dpd'">Dubbing director</xsl:map-entry>
      <xsl:map-entry key="'dpt'">Depositor</xsl:map-entry>
      <xsl:map-entry key="'drm'">Draftsman</xsl:map-entry>
      <xsl:map-entry key="'drt'">Director</xsl:map-entry>
      <xsl:map-entry key="'dsr'">Designer</xsl:map-entry>
      <xsl:map-entry key="'dst'">Distributor</xsl:map-entry>
      <xsl:map-entry key="'dtc'">Data contributor</xsl:map-entry>
      <xsl:map-entry key="'dte'">Dedicatee</xsl:map-entry>
      <xsl:map-entry key="'dtm'">Data manager</xsl:map-entry>
      <xsl:map-entry key="'dto'">Dedicator</xsl:map-entry>
      <xsl:map-entry key="'dub'">Dubious author</xsl:map-entry>
      <xsl:map-entry key="'edc'">Editor of compilation</xsl:map-entry>
      <xsl:map-entry key="'edd'">Editorial director</xsl:map-entry>
      <xsl:map-entry key="'edm'">Editor of moving image work</xsl:map-entry>
      <xsl:map-entry key="'edt'">Editor</xsl:map-entry>
      <xsl:map-entry key="'egr'">Engraver</xsl:map-entry>
      <xsl:map-entry key="'elg'">Electrician</xsl:map-entry>
      <xsl:map-entry key="'elt'">Electrotyper</xsl:map-entry>
      <!-- "emb"/"Ensemble" is special addition -->
      <xsl:map-entry key="'emb'">Ensemble</xsl:map-entry>
      <xsl:map-entry key="'eng'">Engineer</xsl:map-entry>
      <xsl:map-entry key="'enj'">Enacting jurisdiction</xsl:map-entry>
      <xsl:map-entry key="'etr'">Etcher</xsl:map-entry>
      <xsl:map-entry key="'evp'">Event place</xsl:map-entry>
      <xsl:map-entry key="'exp'">Expert</xsl:map-entry>
      <xsl:map-entry key="'fac'">Facsimilist</xsl:map-entry>
      <xsl:map-entry key="'fds'">Film distributor</xsl:map-entry>
      <xsl:map-entry key="'fld'">Field director</xsl:map-entry>
      <xsl:map-entry key="'flm'">Film editor</xsl:map-entry>
      <xsl:map-entry key="'fmd'">Film director</xsl:map-entry>
      <xsl:map-entry key="'fmk'">Filmmaker</xsl:map-entry>
      <xsl:map-entry key="'fmo'">Former owner</xsl:map-entry>
      <xsl:map-entry key="'fmp'">Film producer</xsl:map-entry>
      <xsl:map-entry key="'fnd'">Funder</xsl:map-entry>
      <xsl:map-entry key="'fon'">Founder</xsl:map-entry>
      <xsl:map-entry key="'fpy'">First party</xsl:map-entry>
      <xsl:map-entry key="'frg'">Forger</xsl:map-entry>
      <xsl:map-entry key="'gis'">Geographic information specialist</xsl:map-entry>
      <xsl:map-entry key="'his'">Host institution</xsl:map-entry>
      <xsl:map-entry key="'hnr'">Honoree</xsl:map-entry>
      <xsl:map-entry key="'hst'">Host</xsl:map-entry>
      <xsl:map-entry key="'ill'">Illustrator</xsl:map-entry>
      <xsl:map-entry key="'ilu'">Illuminator</xsl:map-entry>
      <xsl:map-entry key="'ins'">Inscriber</xsl:map-entry>
      <xsl:map-entry key="'inv'">Inventor</xsl:map-entry>
      <xsl:map-entry key="'isb'">Issuing body</xsl:map-entry>
      <xsl:map-entry key="'itr'">Instrumentalist</xsl:map-entry>
      <xsl:map-entry key="'ive'">Interviewee</xsl:map-entry>
      <xsl:map-entry key="'ivr'">Interviewer</xsl:map-entry>
      <xsl:map-entry key="'jud'">Judge</xsl:map-entry>
      <xsl:map-entry key="'jug'">Jurisdiction governed</xsl:map-entry>
      <xsl:map-entry key="'lbr'">Laboratory</xsl:map-entry>
      <xsl:map-entry key="'lbt'">Librettist</xsl:map-entry>
      <xsl:map-entry key="'ldr'">Laboratory director</xsl:map-entry>
      <xsl:map-entry key="'led'">Lead</xsl:map-entry>
      <xsl:map-entry key="'lee'">Libelee-appellee</xsl:map-entry>
      <xsl:map-entry key="'lel'">Libelee</xsl:map-entry>
      <xsl:map-entry key="'len'">Lender</xsl:map-entry>
      <xsl:map-entry key="'let'">Libelee-appellant</xsl:map-entry>
      <xsl:map-entry key="'lgd'">Lighting designer</xsl:map-entry>
      <xsl:map-entry key="'lie'">Libelant-appellee</xsl:map-entry>
      <xsl:map-entry key="'lil'">Libelant</xsl:map-entry>
      <xsl:map-entry key="'lit'">Libelant-appellant</xsl:map-entry>
      <xsl:map-entry key="'lsa'">Landscape architect</xsl:map-entry>
      <xsl:map-entry key="'lse'">Licensee</xsl:map-entry>
      <xsl:map-entry key="'lso'">Licensor</xsl:map-entry>
      <xsl:map-entry key="'ltg'">Lithographer</xsl:map-entry>
      <xsl:map-entry key="'lyr'">Lyricist</xsl:map-entry>
      <xsl:map-entry key="'mcp'">Music copyist</xsl:map-entry>
      <xsl:map-entry key="'mdc'">Metadata contact</xsl:map-entry>
      <xsl:map-entry key="'med'">Medium</xsl:map-entry>
      <xsl:map-entry key="'mfp'">Manufacture place</xsl:map-entry>
      <xsl:map-entry key="'mfr'">Manufacturer</xsl:map-entry>
      <xsl:map-entry key="'mka'">Makeup artist</xsl:map-entry>
      <xsl:map-entry key="'mod'">Moderator</xsl:map-entry>
      <xsl:map-entry key="'mon'">Monitor</xsl:map-entry>
      <xsl:map-entry key="'mrb'">Marbler</xsl:map-entry>
      <xsl:map-entry key="'mrk'">Markup editor</xsl:map-entry>
      <xsl:map-entry key="'msd'">Musical director</xsl:map-entry>
      <xsl:map-entry key="'mte'">Metal-engraver</xsl:map-entry>
      <xsl:map-entry key="'mtk'">Minute taker</xsl:map-entry>
      <xsl:map-entry key="'mup'">Music programmer</xsl:map-entry>
      <xsl:map-entry key="'mus'">Musician</xsl:map-entry>
      <xsl:map-entry key="'mxe'">Mixing engineer</xsl:map-entry>
      <xsl:map-entry key="'nan'">News anchor</xsl:map-entry>
      <xsl:map-entry key="'nrt'">Narrator</xsl:map-entry>
      <xsl:map-entry key="'onp'">Onscreen participant</xsl:map-entry>
      <xsl:map-entry key="'opn'">Opponent</xsl:map-entry>
      <xsl:map-entry key="'org'">Originator</xsl:map-entry>
      <xsl:map-entry key="'orm'">Organizer</xsl:map-entry>
      <xsl:map-entry key="'osp'">Onscreen presenter</xsl:map-entry>
      <xsl:map-entry key="'oth'">Other</xsl:map-entry>
      <xsl:map-entry key="'own'">Owner</xsl:map-entry>
      <xsl:map-entry key="'pad'">Place of address</xsl:map-entry>
      <xsl:map-entry key="'pan'">Panelist</xsl:map-entry>
      <xsl:map-entry key="'pat'">Patron</xsl:map-entry>
      <xsl:map-entry key="'pbd'">Publishing director</xsl:map-entry>
      <xsl:map-entry key="'pbl'">Publisher</xsl:map-entry>
      <xsl:map-entry key="'pdr'">Project director</xsl:map-entry>
      <xsl:map-entry key="'pfr'">Proofreader</xsl:map-entry>
      <xsl:map-entry key="'pht'">Photographer</xsl:map-entry>
      <xsl:map-entry key="'plt'">Platemaker</xsl:map-entry>
      <xsl:map-entry key="'pma'">Permitting agency</xsl:map-entry>
      <xsl:map-entry key="'pmn'">Production manager</xsl:map-entry>
      <xsl:map-entry key="'pop'">Printer of plates</xsl:map-entry>
      <xsl:map-entry key="'ppm'">Papermaker</xsl:map-entry>
      <xsl:map-entry key="'ppt'">Puppeteer</xsl:map-entry>
      <xsl:map-entry key="'pra'">Praeses</xsl:map-entry>
      <xsl:map-entry key="'prc'">Process contact</xsl:map-entry>
      <xsl:map-entry key="'prd'">Production personnel</xsl:map-entry>
      <xsl:map-entry key="'pre'">Presenter</xsl:map-entry>
      <xsl:map-entry key="'prf'">Performer</xsl:map-entry>
      <xsl:map-entry key="'prg'">Programmer</xsl:map-entry>
      <xsl:map-entry key="'prm'">Printmaker</xsl:map-entry>
      <xsl:map-entry key="'prn'">Production company</xsl:map-entry>
      <xsl:map-entry key="'pro'">Producer</xsl:map-entry>
      <xsl:map-entry key="'prp'">Production place</xsl:map-entry>
      <xsl:map-entry key="'prs'">Production designer</xsl:map-entry>
      <xsl:map-entry key="'prt'">Printer</xsl:map-entry>
      <xsl:map-entry key="'prv'">Provider</xsl:map-entry>
      <xsl:map-entry key="'pta'">Patent applicant</xsl:map-entry>
      <xsl:map-entry key="'pte'">Plaintiff-appellee</xsl:map-entry>
      <xsl:map-entry key="'ptf'">Plaintiff</xsl:map-entry>
      <xsl:map-entry key="'pth'">Patent holder</xsl:map-entry>
      <xsl:map-entry key="'ptt'">Plaintiff-appellant</xsl:map-entry>
      <xsl:map-entry key="'pup'">Publication place</xsl:map-entry>
      <xsl:map-entry key="'rap'">Rapporteur</xsl:map-entry>
      <xsl:map-entry key="'rbr'">Rubricator</xsl:map-entry>
      <xsl:map-entry key="'rcd'">Recordist</xsl:map-entry>
      <xsl:map-entry key="'rce'">Recording engineer</xsl:map-entry>
      <xsl:map-entry key="'rcp'">Addressee</xsl:map-entry>
      <xsl:map-entry key="'rdd'">Radio director</xsl:map-entry>
      <xsl:map-entry key="'red'">Redaktor</xsl:map-entry>
      <xsl:map-entry key="'ren'">Renderer</xsl:map-entry>
      <xsl:map-entry key="'res'">Researcher</xsl:map-entry>
      <xsl:map-entry key="'rev'">Reviewer</xsl:map-entry>
      <xsl:map-entry key="'rpc'">Radio producer</xsl:map-entry>
      <xsl:map-entry key="'rps'">Repository</xsl:map-entry>
      <xsl:map-entry key="'rpt'">Reporter</xsl:map-entry>
      <xsl:map-entry key="'rpy'">Responsible party</xsl:map-entry>
      <xsl:map-entry key="'rse'">Respondent-appellee</xsl:map-entry>
      <xsl:map-entry key="'rsg'">Restager</xsl:map-entry>
      <xsl:map-entry key="'rsp'">Respondent</xsl:map-entry>
      <xsl:map-entry key="'rsr'">Restorationist</xsl:map-entry>
      <xsl:map-entry key="'rst'">Respondent-appellant</xsl:map-entry>
      <xsl:map-entry key="'rth'">Research team head</xsl:map-entry>
      <xsl:map-entry key="'rtm'">Research team member</xsl:map-entry>
      <xsl:map-entry key="'rxa'">Remix artist</xsl:map-entry>
      <xsl:map-entry key="'sad'">Scientific advisor</xsl:map-entry>
      <xsl:map-entry key="'sce'">Scenarist</xsl:map-entry>
      <xsl:map-entry key="'scl'">Sculptor</xsl:map-entry>
      <xsl:map-entry key="'scr'">Scribe</xsl:map-entry>
      <xsl:map-entry key="'sde'">Sound engineer</xsl:map-entry>
      <xsl:map-entry key="'sds'">Sound designer</xsl:map-entry>
      <xsl:map-entry key="'sec'">Secretary</xsl:map-entry>
      <xsl:map-entry key="'sfx'">Special effects provider</xsl:map-entry>
      <xsl:map-entry key="'sgd'">Stage director</xsl:map-entry>
      <xsl:map-entry key="'sgn'">Signer</xsl:map-entry>
      <xsl:map-entry key="'sht'">Supporting host</xsl:map-entry>
      <xsl:map-entry key="'sll'">Seller</xsl:map-entry>
      <xsl:map-entry key="'sng'">Singer</xsl:map-entry>
      <xsl:map-entry key="'spk'">Speaker</xsl:map-entry>
      <xsl:map-entry key="'spn'">Sponsor</xsl:map-entry>
      <xsl:map-entry key="'spy'">Second party</xsl:map-entry>
      <xsl:map-entry key="'srv'">Surveyor</xsl:map-entry>
      <xsl:map-entry key="'std'">Set designer</xsl:map-entry>
      <xsl:map-entry key="'stg'">Setting</xsl:map-entry>
      <xsl:map-entry key="'stl'">Storyteller</xsl:map-entry>
      <xsl:map-entry key="'stm'">Stage manager</xsl:map-entry>
      <xsl:map-entry key="'stn'">Standards body</xsl:map-entry>
      <xsl:map-entry key="'str'">Stereotyper</xsl:map-entry>
      <xsl:map-entry key="'swd'">Software developer</xsl:map-entry>
      <xsl:map-entry key="'tau'">Television writer</xsl:map-entry>
      <xsl:map-entry key="'tcd'">Technical director</xsl:map-entry>
      <xsl:map-entry key="'tch'">Teacher</xsl:map-entry>
      <xsl:map-entry key="'ths'">Thesis advisor</xsl:map-entry>
      <xsl:map-entry key="'tld'">Television director</xsl:map-entry>
      <xsl:map-entry key="'tlg'">Television guest</xsl:map-entry>
      <xsl:map-entry key="'tlh'">Television host</xsl:map-entry>
      <xsl:map-entry key="'tlp'">Television producer</xsl:map-entry>
      <xsl:map-entry key="'trc'">Transcriber</xsl:map-entry>
      <xsl:map-entry key="'trl'">Translator</xsl:map-entry>
      <xsl:map-entry key="'tyd'">Type designer</xsl:map-entry>
      <xsl:map-entry key="'tyg'">Typographer</xsl:map-entry>
      <xsl:map-entry key="'uvp'">University place</xsl:map-entry>
      <xsl:map-entry key="'vac'">Voice actor</xsl:map-entry>
      <xsl:map-entry key="'vdg'">Videographer</xsl:map-entry>
      <xsl:map-entry key="'vfx'">Visual effects provider</xsl:map-entry>
      <xsl:map-entry key="'wac'">Writer of added commentary</xsl:map-entry>
      <xsl:map-entry key="'wal'">Writer of added lyrics</xsl:map-entry>
      <xsl:map-entry key="'wam'">Writer of accompanying material</xsl:map-entry>
      <xsl:map-entry key="'wat'">Writer of added text</xsl:map-entry>
      <xsl:map-entry key="'wdc'">Woodcutter</xsl:map-entry>
      <xsl:map-entry key="'wde'">Wood engraver</xsl:map-entry>
      <xsl:map-entry key="'win'">Writer of introduction</xsl:map-entry>
      <xsl:map-entry key="'wit'">Witness</xsl:map-entry>
      <xsl:map-entry key="'wpr'">Writer of preface</xsl:map-entry>
      <xsl:map-entry key="'wst'">Writer of supplementary textual content</xsl:map-entry>
    </xsl:map>
  </xsl:variable>
</xsl:stylesheet>
